"""Pydantic schemas for request and response models."""
from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class HealthResponse(BaseModel):
    """Health check response."""
    status: str = Field(..., example="ok")
    service: str = Field(..., example="JobLens AI backend")
    version: str = Field(..., example="0.1.0")
    bedrock_configured: bool = Field(False, description="Whether Amazon Bedrock is configured with credentials")


class ExtractedDocument(BaseModel):
    """Extracted text data from a resume or job description."""
    filename: Optional[str] = Field(None, description="Original filename if uploaded")
    source: Literal["pdf", "text"] = Field(..., description="Source of the text (pdf upload or raw text)")
    page_count: Optional[int] = Field(None, description="Number of pages if extracted from PDF")
    text_length: int = Field(..., description="Character count of cleaned extracted text")
    text: Optional[str] = Field(None, description="Cleaned extracted text content")


class SkillGapSchema(BaseModel):
    """A missing or weak skill identified from the job description."""
    skill: str = Field(..., description="Name of the required skill or technology")
    priority: Literal["high", "medium", "low"] = Field(..., description="Urgency/importance of the gap")
    reason: str = Field(..., description="Evidence-based explanation of why this is a gap")


class RoadmapItemSchema(BaseModel):
    """A day-by-day learning action item."""
    day: int = Field(..., ge=1, le=30, description="Day number in preparation sequence (e.g. 1 to 5)")
    topic: str = Field(..., description="Core subject / skill to study or practice")
    priority: Literal["high", "medium", "low"] = Field("high", description="Priority level")
    activity: str = Field(..., description="Specific actionable task, mini-project, or tutorial")
    effort: str = Field(..., description="Estimated time effort (e.g. '2-3 hours')")
    reason: str = Field(..., description="Why this activity addresses key job requirements")


class InterviewQuestionSchema(BaseModel):
    """An interview question tailored to the role and candidate profile."""
    category: Literal["technical", "resume", "behavioral", "job-specific"] = Field(
        ..., description="Question classification category"
    )
    question: str = Field(..., description="The interview question text")
    hint: Optional[str] = Field(None, description="Guidance or suggested answering framework")


class AnalysisResultSchema(BaseModel):
    """Structured career intelligence analysis generated by Amazon Bedrock."""
    match_score: int = Field(..., ge=0, le=100, description="Compatibility estimate from 0-100")
    match_category: str = Field(..., description="Category: e.g. Excellent Match, Strong Match, Moderate Match, Needs Improvement")
    summary: str = Field(..., description="Overall executive summary of candidate fit")
    matching_skills: List[str] = Field(default_factory=list, description="Skills verified in both resume and JD")
    skill_gaps: List[SkillGapSchema] = Field(default_factory=list, description="Important requirements not demonstrated in resume")
    strengths: List[str] = Field(default_factory=list, description="Key candidate strengths relevant to the target role")
    weaknesses: List[str] = Field(default_factory=list, description="Areas where candidate profile is weakest for this role")
    important_requirements: List[str] = Field(default_factory=list, description="Core requirements highlighted from the job description")
    priority_gaps: List[SkillGapSchema] = Field(default_factory=list, description="Top high/medium priority gaps to address first")
    learning_roadmap: List[RoadmapItemSchema] = Field(default_factory=list, description="Day-by-day personalized preparation action plan")
    interview_questions: List[InterviewQuestionSchema] = Field(default_factory=list, description="Curated interview questions")


class AnalyzeResponse(BaseModel):
    """Response returned by the document analysis ingestion endpoint."""
    success: bool = True
    message: str = "Analysis completed successfully."
    mode: Literal["bedrock_ai", "mock_preview"] = Field(
        "bedrock_ai", description="Mode indicating if response was generated by live Bedrock AI or preview fallback"
    )
    model_id: Optional[str] = Field(None, description="Amazon Bedrock model ID used for inference")
    resume: ExtractedDocument
    job_description: ExtractedDocument
    analysis: AnalysisResultSchema


# =====================================================================
# Phase 4 — AI Interview Coach Schemas
# =====================================================================

class InterviewEvaluateRequest(BaseModel):
    """Request payload to evaluate a candidate's answer to an interview question."""
    question: str = Field(..., min_length=5, description="The interview question being answered")
    category: Literal["technical", "resume", "behavioral", "job-specific"] = Field(
        "technical", description="Question category"
    )
    answer: str = Field(..., min_length=10, max_length=10000, description="The candidate's response text")
    job_description: Optional[str] = Field(None, description="Target job description context")
    resume_context: Optional[str] = Field(None, description="Candidate resume context")


class InterviewEvaluationSchema(BaseModel):
    """Structured evaluation feedback generated by Amazon Bedrock for an interview answer."""
    overall_score: int = Field(..., ge=0, le=10, description="Overall score from 0 to 10")
    relevance_score: int = Field(..., ge=0, le=10, description="How well the answer addressed the specific question (0-10)")
    technical_score: int = Field(..., ge=0, le=10, description="Technical depth, accuracy, or framework adherence (0-10)")
    clarity_score: int = Field(..., ge=0, le=10, description="Structure, communication clarity, and conciseness (0-10)")
    completeness_score: int = Field(..., ge=0, le=10, description="Coverage of critical concepts and examples (0-10)")
    strengths: List[str] = Field(default_factory=list, description="What the candidate did well in the answer")
    missing_points: List[str] = Field(default_factory=list, description="Key concepts or details that were missing")
    improvement_tips: List[str] = Field(default_factory=list, description="Actionable advice on how to improve this answer")
    suggested_better_answer: str = Field(..., description="An exemplary model answer demonstrating best practices")
    final_feedback: str = Field(..., description="Summary coaching feedback and encouragement")


class InterviewEvaluateResponse(BaseModel):
    """Response returned by the interview evaluation endpoint."""
    success: bool = True
    message: str = "Answer evaluated successfully."
    mode: Literal["bedrock_ai", "mock_preview"] = Field(
        "bedrock_ai", description="Mode indicating live Bedrock AI or preview fallback"
    )
    model_id: Optional[str] = Field(None, description="Amazon Bedrock model ID used for evaluation")
    evaluation: InterviewEvaluationSchema


class ErrorResponse(BaseModel):
    """Standard error response."""
    success: bool = False
    error: str = Field(..., description="User-friendly error summary")
    detail: Optional[str] = Field(None, description="Optional extra detail or guidance")
